### ISSUE TITLE
Fix imports after code refactoring for all layouts/views

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#107]
On develop branch, we've refactored the codebase to conform to the current recommended application structure in the Meteor docs, and we need to resolve a few remaining import errors by importing packages and components across the application.

**Comment by sunsheeppoplar** [comment]
I assume the setup for the app is the same as currently described in the docs? After that, just start following the trail of import errors?

**Comment by sunsheeppoplar** [comment]
Also, what's the convention y'all use for branch naming?

**Comment by lukehollis** [comment]
Hi, @sunsheeppoplar, yep, that's right! The readme info on getting started should be up to date, and if you run into any issues, we'll be on the cltk_frontend gitter. For branch naming, we generally try to follow the git-flow model from that article a few years ago: http://nvie.com/posts/a-successful-git-branching-model/ Master is used for releases, develop for active development, and finally feature/fix/etc branches for major features. I don't like to squash and merge when moving back to develop, but I know some others in the past have preferred to, so I think that's mostly at the volition of the developer! Let me know if there's any other info I can provide.
