### ISSUE TITLE
Update frontend styles/templates for Home View

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#108]
![00](https://user-images.githubusercontent.com/2633382/27508978-cfa3d15a-58bf-11e7-8112-b8853605c41e.jpg)

**Comment by chandanakgd** [comment]
Can you give me a briefly introduction about the issue . Do you ask to implement the web page working correctly.
I see search result didn't give any thing Is that the problem in this? and I would like to contribute this issue

**Comment by lukehollis** [comment]
Hi @chandanakgd thanks for reaching out. We need to update the frontend React components and LESS stylesheets to make sure that the homepage styles are updated to look like the new layout for the homepage. Here is the directory for the homepage components: https://github.com/cltk/cltk_frontend/tree/develop/imports/ui/components/home

**Comment by lukehollis** [comment]
Also, @chandanakgd, thanks for submitting your feedback about the search tools. I've created an issue on the textserver repo here: https://github.com/cltk/texts_server/issues/3
