### ISSUE TITLE
Deep linking search filters with URL

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#19]

**Comment by manu-chroma** [comment]
@lukehollis Can you provide more details regarding the issue ?

**Comment by lukehollis** [comment]
We will need to make search filters affect some kind of parameters in the URL that may be parsed if present on page load.  These parameters will update the filters selected in the search tools, kind of like the way this link https://devart.withgoogle.com/#/?q=javascript selects "Javascript" as a search filter in the search tools on that website. 

In order to build this, we will need to first build the search tools.

**Comment by manu-chroma** [comment]
If I'm not wrong this issue is directly related to the design of the API rather than frontend itself. Right ?

**Comment by lukehollis** [comment]
This is an issue related to the way the frontend application will build a query to be put in place of this one (which returns all works--only "{}"--the search filters need to be added here by our search tools) on the WorksList view: https://github.com/cltk/cltk_frontend/blob/master/client/views/works/WorksList.jsx#L11

This does not access the cltk_api Flask application, but rather leverages Meteor's internal websockets connection.

**Comment by lukehollis** [comment]
Closed with https://github.com/cltk/cltk_frontend/commit/5b7e9da0b866675d39f60d572504fe91eaf88b1f
