### ISSUE TITLE
Infinite scroll for reading interface

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#27]

**Comment by sameeriitkgp** [comment]
@lukehollis I'm interested.

**Comment by lukehollis** [comment]
Great. Our reading environment class will need a method for getting more text for a given work when a user reaches the bottom of the page: https://github.com/cltk/cltk_frontend/blob/master/client/views/reading/reading.jsx

The query for more text will need to look something like the query already in place here: https://github.com/cltk/cltk_frontend/blob/master/client/views/reading/reading.jsx#L18

In order to move forward on this issue, we will first need to restructure the Reading templates based on the document formats described here: https://github.com/cltk/cltk_api/issues/12
