### ISSUE TITLE
Retrieve text from API

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#34]

**Comment by shubhams** [comment]
@lukehollis I would like to work on this issue. Please add relevant information.

**Comment by lukehollis** [comment]
Thanks, @shubham12101. We need to sync text document data from the API to the Meteor database.  The beginnings of this process in the Meteor application are here: https://github.com/cltk/cltk_frontend/blob/master/server/text-server-sync.js  This script currently fetches languages, corpora, authors, works, and texts from the API and syncs all content on application startup.  When we run this in production, we will need to setup a better system of cache invalidation for documents in the CLTK collection so that the text-server-sync may run at an interval to update data in Mongo database.

**Comment by lukehollis** [comment]
I've split off two outstanding related issues that are related to this one:
Regarding cache invalidation: https://github.com/cltk/cltk_frontend/issues/24
Regarding text server sync for multiple document formats: https://github.com/cltk/cltk_frontend/issues/43
