### ISSUE TITLE
Add networked text / linked data modules to frontend

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#36]
This is an issue for the longer-term epic-sized task of retrieving metadata about text (definitions, related passages, translations, etc.) from the cltk_api. As much as is useful, we should split smaller issues related to retrieving metadata from the api into their own issues.

**Comment by Alpus** [comment]
That issue looks interesting for me, but there is no specific steps which I supposed to follow. I think we need to discuss something like PRD in order to organize work in a more productive way. Now, I just can't find out what exactly I should to do.

**Comment by lukehollis** [comment]
Hi @Alpus--Did you receive my email on March 16th? This issue represents a complex undertaking that needs to be divided in to several smaller issues in future iterations of the project. Please respond to my email with specific questions about what you're interested in working on, and I'll respond with how to get started.

**Comment by lukehollis** [comment]
Much development done in this area. Seems worthwhile to close the epic now and deal with other issues separately to avoid confusion.
