### ISSUE TITLE
Toggle between translations

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#38]
<img width="551" alt="screen shot 2016-03-13 at 00 31 51" src="https://cloud.githubusercontent.com/assets/2633382/13727110/0933eb68-e8b3-11e5-8497-edca8ccc69c5.png">
We need to be able to toggle between multiple translations using the buttons at the bottom of the translation panel.

**Comment by manu-chroma** [comment]
I would like to implement this feature if the backbone is already present.

**Comment by lukehollis** [comment]
Thanks, @manu-chroma, you will be able to implement this feature with the two translations in the array here: https://github.com/cltk/cltk_frontend/blob/e03368238c7d44fe8d939ef3ede216037332de95/client/views/reading/CommentaryPanel.jsx#L17 You will just need to add a function bound to a click event on the commentary panel that selects the translation each button indicates. Let me know if there's anything else you need here to get started.

**Comment by manu-chroma** [comment]
Thanks @lukehollis, I will. You can assign this one to me.
