### ISSUE TITLE
Text Sync should handle all document formats (chapter, book-chapter, book-chapter-section, book-line, poem-line, etc.)

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#43]
We need to work in tandem with the development ongoing for document conversion (issue here: https://github.com/cltk/cltk_api/issues/11) to stabilize the document format and ingest it correctly into the Meteor application's Mongo database.

The current text-server-sync script does not ingest every document format.  

Before move forward, we need to stabilize and specify what all document formats should look like.

**Comment by lukehollis** [comment]
Issue on the API repo here: https://github.com/cltk/cltk_api/issues/12

**Comment by sameeriitkgp** [comment]
@lukehollis That's a great idea.
We should first decide on how the json file should look like.
That will make the document conversion process Specific.

**Comment by kylepjohnson** [comment]
Any changes you need to the flask API, let me know or find someone to assign, and I'll give guidance. I'm replying still to a lot of application inquiries, so can't code myself on this for the next week or so.

**Comment by suheb** [comment]
@lukehollis @kylepjohnson I can work on this. Let me know where to start.

**Comment by lukehollis** [comment]
I don't think we need any changes to the flask API but perhaps can build something that's flexible / somewhat agnostic of what the levels of nesting are. Thanks, @suheb. This is a complex but critical task that will involve changing the collection schema for Texts, renaming the n, book, and chapter fields to something more generalized, such as n_1, n_2, and n_3. It doesn't seems like there's content nested more than 3 levels deep, but this might change in the future, in which case we can add an n_4 or more the n_\* fields to an ordered list. Thoughts/perspectives on this? Building frontend templates for more than five document formats (chapter, book-chapter, book-chapter-section, book-line, poem-line, etc.) might be simplified if we just build for varying amounts of nested content. 

For book 1, chapter 2, section 3 in a response from the API that look like this:

``` json
"1":{
   "1":{
      ... 
   },
   "2":{
      "1": ...,
      "2": ...,
      "3": "Quid faciat laetas segetes quo sidere terram .... etc.",
      ...
   },
   ...
},
...
```

we will need to create an object on the text sync like this:

``` json
{
   "n_1" : 1,
   "n_2": 2,
   "n_3": 3,
   "text": "quid faciat laetas segetes quo sidere terram",
   ...etc.
}
```

If there are only two levels of nested content, n_3 should be null. If there is only one, n_2 should be null.

The frontend ReadingBook.jsx, ReadingChapter.jsx, ReadingText.jsx templates should be restructured to accommodate text objects with only n_1 set, only n_1 and n_2 set, or n_1, n_2, and n_3 set.  ReadingProse.jsx and ReadingPoetry.jsx might be able to be restructured as a part of this as well. 

The text-sync script will need to be updated to reflect these changes as well.  

But again, I'm very open to suggestion here. I think there are a lot of good possible solutions. We can make this more complex as need be--I think the only thing to avoid is over-optimizing prematurely for use cases that are marginal and/or non-existent.

**Comment by lukehollis** [comment]
Worked together the modified collection and text sync here, but this needs further testing to ensure all content is syncing properly: https://github.com/cltk/cltk_frontend/blob/master/server/text-server-sync.js

One issue that needs more investigation is not all keys in the JSON response can be parsed as integers.

**Comment by lukehollis** [comment]
We've moved past syncing data from the text server to importing it manually one way or another, so this is ready to be closed.
