### ISSUE TITLE
Changing font-weight for input and changing padding size for links

### ISSUE THREAD

**Issue by ghost** [cltk/cltk_frontend#53]
Hello, I have two questions
1) the font-weight for <code>input, select, textarea</code> tags seems to be too less that it is too difficult to use/recognize. So I want to change the font weight to bold. That is 
from this to:
![screenshot from 2016-03-15 17 26 28](https://cloud.githubusercontent.com/assets/6941077/13777132/24546364-ead4-11e5-9303-9edb51aeeba0.png)

this:
![screenshot from 2016-03-15 17 27 28](https://cloud.githubusercontent.com/assets/6941077/13777147/3840018a-ead4-11e5-973f-006c96010567.png)

Also, I think we need to increase the padding-bottom for links so that it looks good. That is
from this to:<br>
![screenshot from 2016-03-15 17 28 56](https://cloud.githubusercontent.com/assets/6941077/13777170/73c4e860-ead4-11e5-9b1a-b2ee78829df6.png)

this:
![screenshot from 2016-03-15 17 28 37](https://cloud.githubusercontent.com/assets/6941077/13777176/7b920f50-ead4-11e5-9ed6-6bdfd1283466.png)

if this looks fine, I will make a PR.

2) Also I am having a small doubt. in the search page: http://api.cltk.org/search
there is only text called "Search" in it. Where as in home page: http://api.cltk.org/
there is an input for search. So can't we just use the same input for search in search page.

Thank you.

**Comment by lukehollis** [comment]
Thanks, @achaitanyasai--#1 above with the visuals for input values sounds good. As far as /search versus the search on the homepage, let's make a new issue.

**Comment by ghost** [comment]
Thanks, I will submit PR with in 10 hours.

**Comment by lukehollis** [comment]
Looks good--thanks!

**Comment by ghost** [comment]
Thank you sir.
