### ISSUE TITLE
Infer basic genre from document metadata structure and select Prose or Poetry reading views based on inferred genre

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#57]
We need to set the most basic details about genre based on the document metadata structure and then select the ReadingProse or ReadingPoetry view based on this.  

We will need to rework ReadingPoetry.jsx as well to display poetry with similar but a little different styles (in a separate issue).

**Comment by lukehollis** [comment]
It has been suggested that we update the "genre" parameter to be "form" instead of genre. The genre would be something like epic, elegy, or pastoral, and form would be prose, poetry, etc. Thoughts?

**Comment by kylepjohnson** [comment]
I can't help with the JS code, but obviously am around to help think through the thornier genre formatting. 

In fact, as I write, this, I wonder whether "genre" is the wrong word, as typically speaking texts of two genres could both be prose. I'm probably being a little bit pedantic but think about calling such templates something different – formatting? layout? mise en page?

**Comment by lukehollis** [comment]
Went back and forth on using the document structure from the JSON versus a parameter set in the database, but now you can set the 'form' parameter on any work in the database.
