### ISSUE TITLE
Display Nested content numbering in title field

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#59]
We will need to display the nested numbering values (n_1, n_2, n_3) in the title field above each work.  The numbers circled in red in this screencap do not yet exist in the templates but should.

<img width="842" alt="screen shot 2016-03-18 at 19 56 12" src="https://cloud.githubusercontent.com/assets/2633382/13895109/bbe5c74a-ed45-11e5-8531-6c665778c663.png">

**Comment by lukehollis** [comment]
This field should be flexible based on the parameters that are set on the Text objects.  If only n_1 is set, only display one field in the title like "#.". If n_1 and n_2 are set, display two fields in the title as "#.#". If n_1, n_2, and n_3 are all set, display them as "#.#.#".

**Comment by suheb** [comment]
Do we want something like this?
![screenshot from 2016-03-19 17 48 06](https://cloud.githubusercontent.com/assets/4609293/13898543/e5010d64-edfa-11e5-993e-1ceac77f3717.png)

**Comment by lukehollis** [comment]
We want to add the title every time the second-to-last most deeply nested number is incremented.  So for instance, if the text objects for this work had n_1, n_2, and n_3 values, we would want to add the title every time n_1 and n_2 changed. 

If the text objects had n_1 and n_2 values set, we would want to add the title every time the n_1 value changed. 

If the text objects only had the n_1 value set, we would want to omit adding the title.  

This is a complicated issue but I think necessary for the flexible layout to render our recursive nesting.  This may add some complex code, but I think it is still more simple than the alternative.

**Comment by lukehollis** [comment]
But the fonts look good! The placement should be slightly to the left.
