### ISSUE TITLE
Get definitions for words from the API and store them locally in the database

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#60]
As a part of https://github.com/cltk/cltk_frontend/issues/36, we will need to retrieve definitions of words from the cltk_api Flask applications and save them to the database to show in the definitions panel. 

This is currently what the definitions panel looks like: 

<img width="546" alt="screen shot 2016-03-18 at 20 30 16" src="https://cloud.githubusercontent.com/assets/2633382/13895318/4b494aae-ed48-11e5-9739-39c511decbf6.png">

In order to do this, we will first need to develop the cltk_api frontend application to feature a dictionary lookup for words. 

The blue Perseus link should link to Perseus's dictionaries with a link such as http://www.perseus.tufts.edu/hopper/morph?l=arma&la=la

**Comment by kylepjohnson** [comment]
Cross-reference in the API issues: https://github.com/cltk/cltk_api/issues/26

**Comment by lukehollis** [comment]
I can be persuaded either way on this, but I think we might be happy with two collections: one for the multiple definitions of a word and the other for the possible forms of the word in a given context. 

First collection ("definitions") needs the following information like a dictionary entry:
armum, armi (noun, 2nd declension): arms (pl.), weapons, armor, shield; close fighting weapons; equipment; force; 

Parameters that may figure into the collection model:
armum, armi: entry for word
noun: part of speech
2nd declension: declension/conjugation information
arms, etc.: word definitions/senses

Second collection ("wordForms"), containing lemmatized information from the CLTK API:
arm-a - neuter nominative plural  
arm-a - neuter accusative plural

Parameters that may figure into the collection model:
arm-a: occurence
neuter nominative plural, etc.: delcension/conjugation information
and also a list of ids to possible definitions for the word

Thoughts about this type of layout?  We should at least consider a little bit how to invalidate our local store of definition / lemmatized word information at this point as well.

**Comment by suheb** [comment]
If I understand this correctly, it makes perfect sense.
We have separate tables for `definitions` and `text`. As we have a many-to-many relationship between `definitions` and `text` (a definition may be present in many texts and a text may contain many definitions), we'll have a separate table for this relationship say, `wordForms` which contains the occurrence of the word, declension/conjugation information, id/ids of definitions and id of the text.
Please correct me if I got it wrong.

**Comment by christophermorse** [comment]
Hi all,

I’ve seen a few different data models for inflected languages — one that treats nouns/verbs/etc. and their respective inflections as individual, unique lemmas, and others (such as what we do with the visualizing Russian project) where all inflections are children of a parent node (in nominative/infinitive). How this translates into the Mongo universe I’m not exactly sure (unfortunately Mongo is not my forte, as Luke knows I am a graph databases person), so I defer to you all on this, though Luke it seems like what you’ve laid out is very sensical!

Chris

**Comment by kylepjohnson** [comment]
Hey all, chiming in about pulling the data from Perseus. @lukehollis are you thinking of hitting Perseus's URL (eg, http://www.perseus.tufts.edu/hopper/morph?l=arma&la=la)? If so, I think this is great, though suggest that we do this once (as a scrape) and not bother with it again. If we persist, I believe JSON/Mongo would be adequate for now. (Perhaps save a large JSON blob to file, then allow for it to be loaded into Mongo/etc).

Another option for you is to use the original Perseus files. I'll warn that this will lead some maddening string manipulation, but is theoretically possible.

My understanding is that this info from the Perseus API is basically a view into the file `latin-analyses.txt` (35MB), which is in the [cltk/latin_pos_lemmata_cltk](https://github.com/cltk/latin_pos_lemmata_cltk/tree/master/perseus_data) repo. So, you'd look at the line 49590 and you'll see the line:

```
arma    {6338412 9 arma     neut nom/voc/acc pl}{6405166 9 arma_,armo   To arm  pres imperat act 2nd sg}
```

Some tips on parsing this:
- The brackets (`{` and `}`) contain each distinct dictionary headword
- The long numbers (`6338412`) are the unique id of each dictionary headword
- I forget what the short number (`9`) means
- The test are typical parts of speech tags, however the order in which they appear might not be always predictable

Then you could look up the headwords in one of the Perseus dictionaries (like [the OLD at cltk/latin_lexica_perseus](https://github.com/cltk/latin_lexica_perseus)).

**Comment by lukehollis** [comment]
@suheb, I think that structure sounds good, and that you've got a good grasp on the issue. Thanks for clarifying the application for other languages, @christophermorse.

@kylepjohnson, thanks for this. It looks like parsing the original Perseus files would be a lot of work--do you think that the value added by this would be much more than parsing the HTML?

**Comment by kylepjohnson** [comment]
> do you think that the value added by this would be much more than parsing the HTML?

@lukehollis No, I do not see any value inherit to parsing the original Perseus files.

**Comment by lukehollis** [comment]
Closed with https://github.com/cltk/cltk_frontend/pull/74
