### ISSUE TITLE
Definitions, Commentary, and Translations panels should scroll asynchronously with source text content

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#62]

**Comment by suheb** [comment]
Does #63 fixes this too?

**Comment by lukehollis** [comment]
These are separate issues. Here's a good example of the asyncronous scrolling feature: http://www.sefaria.org/Genesis.1?lang=en&layout=block&sidebarLang=all

As you scroll in the text, the side panel scrolls with you. 

I could see this being annoying as a user if you wanted to go back to something in the text or commentary but not lose your place, so perhaps we should implement a toggle to turn on/off asynchronous scroll. The toggle should implement this component: http://www.material-ui.com/#/components/toggle

**Comment by suheb** [comment]
After reading your comment on #67, I think this issue might be a little more complex than I first thought.
To implement this, we'd need to change the structure of commentary/translations/definitions to provide a mapping with source text. I gather we already such mapping in commentary demo data present in [CommentaryPanel.jsx](https://github.com/cltk/cltk_frontend/blob/master/client/views/reading/CommentaryPanel.jsx), but I couldn't fully undestand it. I am little confused as to what the `subwork` and `text_n` fields represent. Could you explain it a bit?

**Comment by lukehollis** [comment]
Hey, @suheb, you're definitely correct about the mapping to the source text. I think that this is still forming as we figure out how best to make pagination work, but in general, I think we want to use the key indicies from the JSON responses to do the mapping.  I'm still convinced that the best way to do the mapping is at the text node (line or paragraph) level.  I think that a lot of the original XML document structure of the Greek and Latin texts was designed to reflect the Loeb editions of texts, but for our purposes, I believe we decided it was okay to render data in a format that was acceptable / useful mostly for the purposes of the reading environment on the frontend. 

All this to say, I believe that the subwork and text_n properties on the Text collection are placeholders to a more flexible solution for locating text nodes from the JSON documents.  Let's follow up here when there are more decisions made about the text node subwork/text_n/general location strategy.

**Comment by lukehollis** [comment]
Side panels may now be scrolled on click instead of asynchronously.
